#!/usr/bin/env python3
"""Build the Queue to Inbox Apple Shortcut XML plist."""

from pathlib import Path
import plistlib


OUT = Path(__file__).with_name("Queue to Inbox.xml")
P = chr(0xFFFC)


ASK_CONTEXT_UUID = "5AAE12E9-F716-4C4A-A4F6-E6F4C5BD5CB1"
SHARED_TEXT_UUID = "14248DC3-261C-4056-91A6-A8ED6C695CDE"
SHARED_URLS_UUID = "C8EBA450-4536-4BD8-A90F-8F5D31F1E46D"
REPEAT_GROUP_UUID = "25DB4CAF-14F0-4E7F-A264-3B2DA10AF1F9"
REPEAT_END_UUID = "FB0DDE37-7264-4979-B6E2-5BB2E0A48A7E"


def action(identifier, params=None):
    return {
        "WFWorkflowActionIdentifier": identifier,
        "WFWorkflowActionParameters": params or {},
    }


def comment(text):
    return action("is.workflow.actions.comment", {"WFCommentActionText": text})


def token_attachment(value):
    return {
        "Value": value,
        "WFSerializationType": "WFTextTokenAttachment",
    }


def text_token(text, attachments=None):
    value = {"string": text}
    if attachments is not None:
        value["attachmentsByRange"] = attachments
    return {
        "Value": value,
        "WFSerializationType": "WFTextTokenString",
    }


def field_text(key, value):
    return {
        "WFItemType": 0,
        "WFKey": text_token(key),
        "WFValue": text_token(value),
    }


def field_text_token(key, text, attachment):
    return {
        "WFItemType": 0,
        "WFKey": text_token(key),
        "WFValue": text_token(text, {"{0, 1}": attachment}),
    }


def field_file_from_repeat_item(key):
    return {
        "WFItemType": 5,
        "WFKey": text_token(key),
        "WFValue": {
            "Value": token_attachment(
                {
                    "Type": "Variable",
                    "VariableName": "Repeat Item",
                }
            ),
            "WFSerializationType": "WFTokenAttachmentParameterState",
        },
    }


def dictionary_field(items):
    return {
        "Value": {
            "WFDictionaryFieldValueItems": items,
        },
        "WFSerializationType": "WFDictionaryFieldValue",
    }


workflow = {
    "WFWorkflowActions": [
        comment(
            "Queue shared items into the personal inbox capture server.\n"
            "- Works from the iOS share sheet\n"
            "- Sends text, links, images, audio, videos, PDFs, and files\n"
            "- Adds optional context to every uploaded item"
        ),
        comment(
            "Shortcuts generated by Shortcuts Playground.\n"
            "Prompt: Build Queue to Inbox, a share-sheet uploader that accepts nearly any shared item and posts each item with optional context to a capture server."
        ),
        comment(
            "Configure the capture server before first use.\n"
            "- Replace the placeholder URL in Get Contents of URL\n"
            "- Replace the bearer token placeholder in the Authorization header"
        ),
        comment(
            "Send shared items to the inbox queue.\n"
            "- Each shared item becomes one multipart request\n"
            "- The payload field contains the original shared item\n"
            "- Metadata fields describe the capture source and context"
        ),
        comment(
            "Prepare link and text fallbacks.\n"
            "- Text uses the original shared input\n"
            "- Get URLs from Input extracts links from that text\n"
            "- These fields protect app shares that do not provide a file"
        ),
        action(
            "is.workflow.actions.gettext",
            {
                "UUID": SHARED_TEXT_UUID,
                "WFTextActionText": text_token(
                    P,
                    {
                        "{0, 1}": {
                            "Type": "ExtensionInput",
                        }
                    },
                ),
            },
        ),
        action(
            "is.workflow.actions.detect.link",
            {
                "UUID": SHARED_URLS_UUID,
                "WFInput": text_token(
                    P,
                    {
                        "{0, 1}": {
                            "OutputName": "Text",
                            "OutputUUID": SHARED_TEXT_UUID,
                            "Type": "ActionOutput",
                        }
                    },
                ),
            },
        ),
        comment(
            "Ask for optional context.\n"
            "- Type context normally, or use keyboard dictation\n"
            "- Leave it blank when the shared item is self-explanatory"
        ),
        action(
            "is.workflow.actions.ask",
            {
                "UUID": ASK_CONTEXT_UUID,
                "WFAskActionPrompt": "Context for this capture? Optional.",
                "WFInputType": "Text",
            },
        ),
        comment(
            "Upload every shared item.\n"
            "- Input uses the items from the share sheet\n"
            "- Repeat Item is sent as the payload file\n"
            "- The context answer is attached to every item"
        ),
        action(
            "is.workflow.actions.repeat.each",
            {
                "GroupingIdentifier": REPEAT_GROUP_UUID,
                "WFControlFlowMode": 0,
                "WFInput": token_attachment({"Type": "ExtensionInput"}),
            },
        ),
        action(
            "is.workflow.actions.downloadurl",
            {
                "Advanced": True,
                "WFURL": text_token("https://capture-api-production-1860.up.railway.app/capture"),
                "WFHTTPMethod": "POST",
                "WFHTTPBodyType": "Form",
                "WFHTTPHeaders": dictionary_field(
                    [
                        field_text("Authorization", "Bearer REPLACE_WITH_CAPTURE_TOKEN"),
                        field_text("Accept", "application/json"),
                    ]
                ),
                "WFRequestVariable": token_attachment(
                    {
                        "Type": "Variable",
                        "VariableName": "Repeat Item",
                    }
                ),
                "WFFormValues": dictionary_field(
                    [
                        field_text("source", "ios-shortcut"),
                        field_text("client", "asher-iphone"),
                        field_text_token(
                            "captured_at",
                            P,
                            {"Type": "CurrentDate"},
                        ),
                        field_text_token(
                            "context",
                            P,
                            {
                                "OutputName": "Provided Input",
                                "OutputUUID": ASK_CONTEXT_UUID,
                                "Type": "ActionOutput",
                            },
                        ),
                        field_text_token(
                            "item_index",
                            P,
                            {
                                "Type": "Variable",
                                "VariableName": "Repeat Index",
                            },
                        ),
                        field_text_token(
                            "shared_item",
                            P,
                            {
                                "Type": "Variable",
                                "VariableName": "Repeat Item",
                            },
                        ),
                        field_text_token(
                            "shared_input_text",
                            P,
                            {
                                "OutputName": "Text",
                                "OutputUUID": SHARED_TEXT_UUID,
                                "Type": "ActionOutput",
                            },
                        ),
                        field_text_token(
                            "shared_urls",
                            P,
                            {
                                "OutputName": "URLs",
                                "OutputUUID": SHARED_URLS_UUID,
                                "Type": "ActionOutput",
                            },
                        ),
                        field_file_from_repeat_item("payload"),
                    ]
                ),
            },
        ),
        action(
            "is.workflow.actions.repeat.each",
            {
                "UUID": REPEAT_END_UUID,
                "GroupingIdentifier": REPEAT_GROUP_UUID,
                "WFControlFlowMode": 2,
            },
        ),
        action(
            "is.workflow.actions.notification",
            {
                "WFNotificationActionTitle": text_token("Queued to Inbox"),
                "WFNotificationActionBody": text_token(
                    "Shared item upload finished. Check the queue server for delivery status."
                ),
            },
        ),
    ],
    "WFWorkflowClientVersion": "2700.0.4",
    "WFWorkflowClientRelease": "26A0000a",
    "WFWorkflowHasOutputFallback": False,
    "WFWorkflowHasShortcutInputVariables": True,
    "WFWorkflowIcon": {
        "WFWorkflowIconGlyphNumber": 59725,
        "WFWorkflowIconStartColor": 3031607807,
    },
    "WFWorkflowImportQuestions": [],
    "WFWorkflowInputContentItemClasses": [
        "WFAppStoreAppContentItem",
        "WFArticleContentItem",
        "WFContactContentItem",
        "WFDateContentItem",
        "WFEmailAddressContentItem",
        "WFGenericFileContentItem",
        "WFImageContentItem",
        "WFiTunesProductContentItem",
        "WFLocationContentItem",
        "WFDCMapsLinkContentItem",
        "WFAVAssetContentItem",
        "WFPDFContentItem",
        "WFPhoneNumberContentItem",
        "WFRichTextContentItem",
        "WFSafariWebPageContentItem",
        "WFStringContentItem",
        "WFURLContentItem",
    ],
    "WFWorkflowMinimumClientVersion": 900,
    "WFWorkflowMinimumClientVersionString": "900",
    "WFWorkflowName": "Queue to Inbox",
    "WFWorkflowOutputContentItemClasses": [],
    "WFWorkflowTypes": ["ActionExtension"],
}


with OUT.open("wb") as f:
    plistlib.dump(workflow, f, fmt=plistlib.FMT_XML, sort_keys=False)

print(OUT)
